stages:
  download:
    cmd: uv run python scripts/download_data.py
    outs:
    - data/raw:
        persist: true
    frozen: true
  prepare:
    cmd: uv run python scripts/prepare_data.py
    deps:
    - configs/data.yaml
    - data/raw
    params:
    - configs/data.yaml:
      - base_dir
      - files
      - join_key
      - target
    outs:
    - data/processed:
        persist: true
