stages:
  download:
    cmd: uv run python scripts/download_data.py
    outs:
    - data/raw:
        persist: true
    frozen: true
  prepare:
    cmd: uv run python scripts/prepare_data.py
    deps:
    - configs/data.yaml
    - data/raw
    params:
    - configs/data.yaml:
      - base_dir
      - files
      - join_key
      - target
    outs:
    - data/processed:
        persist: true
  train:
    cmd: uv run python -m src.models.train
    deps:
    - configs/train.yaml
    - configs/features.yaml
    - configs/data.yaml
    - src/models/
    - src/features/
    - src/schemas/
    - data/processed
    params:
    - configs/train.yaml:
      - model
      - split
      - early_stopping
    outs:
    - models/pipeline.joblib
  evaluate:
    cmd: uv run python -m src.models.evaluate
    deps:
    - configs/train.yaml
    - configs/features.yaml
    - configs/data.yaml
    - src/models/
    - src/features/
    - src/schemas/
    - data/processed
    - models/pipeline.joblib
